<Project>
  <ItemGroup Condition="'$(ExcludeSourceLink)' != 'true'">
	<PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.*" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup>
	<None Include="..\..\..\..\icon.png" Pack="true" Visible="false" PackagePath="\" />
  </ItemGroup>
  <PropertyGroup>
	<AspnetVersion>10.*</AspnetVersion>
	<BaseNamespace>Light</BaseNamespace>
	<OrgName>Lightsoft</OrgName>
	<NugetVersion>2.0.0-preview.1</NugetVersion>
  </PropertyGroup>
</Project>