name: "Setup .NET"
description: "Setup .NET"

inputs:
  dotnet-version:
    type: string
    default: '10.x'   # ✅ default value
    required: false
  
runs:

  using: "composite"

  steps:

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

