<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<RootNamespace>$(RootName)</RootNamespace>
	<AssemblyName>$(OrgName).AspNetCore.Extensions</AssemblyName>
	<Title>$(OrgName).AspNetCore.Extensions</Title>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	<Authors>minhvu</Authors>
	<Description>Package containing useful AspNetCore extensions.</Description>
	<Summary>Package containing useful AspNetCore extensions.</Summary>
	<Version>$(NugetVersion)</Version>
	<PackageTags>lightframework;dotnet;aspnetcore</PackageTags>
	<PackageIcon>icon.png</PackageIcon>
	<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	<PublishRepositoryUrl>true</PublishRepositoryUrl>
	<EmbedUntrackedSources>true</EmbedUntrackedSources>
	<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.*" />
	<PackageReference Include="Lightsoft.Result" Version="2.*" />
	<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="$(AspnetVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharedKernel\SharedKernel.csproj" />
  </ItemGroup>

</Project>
