<Project>
  <PropertyGroup>
	<AspnetVersion>10.*</AspnetVersion>
	<BaseNamespace>Light</BaseNamespace>
	<OrgName>Lightsoft</OrgName>
	<NugetVersion>2.0.0</NugetVersion>
	<AuthorizationVersion>$(NugetVersion)</AuthorizationVersion>
	<CachingVersion>$(NugetVersion)</CachingVersion>
	<EntityFrameworkCoreVersion>$(NugetVersion)</EntityFrameworkCoreVersion>
	<ExtensionsVersion>2.0.1-preview.2</ExtensionsVersion>
	<ModularityVersion>$(NugetVersion)</ModularityVersion>
	<SharedKernelVersion>$(NugetVersion)</SharedKernelVersion>
	<SpecificationVersion>$(NugetVersion)</SpecificationVersion>
	<SwaggerVersion>$(NugetVersion)</SwaggerVersion>
	<WebHostVersion>$(NugetVersion)</WebHostVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == ''">
	<TargetFramework>net10.0</TargetFramework>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup Condition="'$(ExcludeSourceLink)' != 'true'">
	<PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.*" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup>
	<None Include="..\..\..\..\icon.png" Pack="true" Visible="false" PackagePath="\" />
  </ItemGroup>
</Project>